### ISSUE TITLE
Which things in knora-base can/must be used as is?

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/dsp-api#138]
Which classes and properties in `knora-base` can/must be used as they are, and which ones can/must be used via subclasses/subproperties? For example:
- `Region`
- `Annotation`
- `LinkObj`
- `ExternalResource`
- `ListNode`
- `isPartOf`
- `isAnnotationOf`

@lrosenth 

Needs #354.

**Comment by mrivoal** [comment]
As this issue came out again last week, I would like to insist on it.

My point is the following: several projects have already expressed their needs to **customize a `Region`**. They would like to define themselves the relevant properties for what would be a `Region` (or a subclass of a `Region`) in their project. Basically, they want to be able to define a property pointing to a hierarchical list for a `Region`, which is currently impossible.

I definitely think that the API v2 and Salsah 2.0 should provide such features in the near future


For the classes `LinkObj`, `Annotation`, it is still not clear to me what they are meant for, so I won't say anything. But regarding `isPartOf`, a project-specific subproperty of `isPartOf` is generally used.

**Comment by benjamingeer** [comment]
Definitely people need to be able to extend these entities. I would be inclined to say that we should require all these entities to be extended rather than used directly. I will talk to @lrosenth about this and see if we can set a clear policy.

**Comment by benjamingeer** [comment]
Closed by mistake.

**Comment by mrivoal** [comment]
What is the status for this issue? Has a policy been defined already? I am asking only because of `Region`, which I would really like to extend. What would it take to you to allow it?

**Comment by mrivoal** [comment]
> It looks to me like the only place in Knora where `knora-base:Region` is really hard-coded is in the `getRegions` SPARQL query in API v1, which is used only in the `reqtype=context` request. I think this could easily be changed to recognise subclasses of `knora-base:Region`.

Do think that we would then have to change the existing data using `knora-base:Region` as well as project ontologies so that they include a project specific region which a subclass of `knora-base:Region`? Or do you plan to support the current schema as well?

> However, there's a lot of hard-coded stuff about regions in the JavaScript code of SALSAH 1.5, and I don't know whether it would be feasible to change it.

No idea. But I guess if we really want to change Salsah 1.5 that will be on us. So, if possible, we will more likely wait for Knora-ui to support regions (including subclasses of `knora-base:Region`).

**Comment by tobiasschweizer** [comment]
> So, if possible, we will more likely wait for Knora-ui to support regions (including subclasses of `knora-base:Region`).

Good point! `IncomingService` gets incoming regions for a given resource (https://github.com/dhlab-basel/Knora-ui/blob/master/projects/knora/core/src/lib/services/v2/incoming.service.ts). It is a Gravsearch query and works with subclasses. But in https://github.com/dhlab-basel/beol/blob/develop/src/app/resource/beol-resource.ts there is still some hard coded properties which would not work with subproperties at the moment. The information is there in the ontology, so I think I will have to refactor that code some day.

**Comment by benjamingeer** [comment]
> Do think that we would then have to change the existing data using `knora-base:Region` as well as project ontologies so that they include a project specific region which a subclass of `knora-base:Region`? Or do you plan to support the current schema as well?

I don’t see any problem with supporting both approaches.

**Comment by mrivoal** [comment]
> The information is there in the ontology, so I think I will have to refactor that code some day.

Maybe let us know when you do. We will see then what we do.

> I don’t see any problem with supporting both approaches.

Great. Thanks.

**Comment by tobiasschweizer** [comment]
> Maybe let us know when you do. We will see then what we do.

I think some of the code in 
https://github.com/dhlab-basel/beol/blob/develop/src/app/resource/beol-resource.ts is actually generic and should be moved to Knora-ui eventually. When this happens, subclass and subproperty relations have to be taken into account. I will coordinate that with you and @kilchenmann. But it won't happen tomorrow ;-)

**Comment by mrivoal** [comment]
> But it won't happen tomorrow ;-)

Yes, I had that in mind :)

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
