### ISSUE TITLE
TimeValue clarification

### ISSUE THREAD

**Issue by mdelez** [dasch-swiss/dsp-api#1604]
After discussing a bit with Lukas, Ivan, and Tobias, it's not entirely clear what the purpose of the TimeValue is. In my mind, the purpose is to allow the user to enter a time of day. However, this causes an issue where Knora only accepts DateTime strings, for example "2019-08-30T10:45:20.173572Z" which means that if we allow the user to only enter a time of day then we will also have to provide a date when we submit the value. So we either also provide the user with a calendar to select a date or, as was recommended by Lukas, we add a placeholder date such as 01.01.1970. Since the date will never be shown to the user through this component, I think Lukas's idea is practical and giving each timestamp the same placeholder date ensures we know which component created the timestamp.

From reading the Knora docs, I know this limitation comes from SPARQL not supporting `xsd:dateTimeStamp` which is quite unfortunate because I believe this causes quite a bit of confusion regarding the fact that we have a TimeValue that returns a DateTime string in addition to having a DateValue that returns a Date, albeit in a different format, but a date nonetheless.

I think this will require some further discussion but for now I will use the idea Lukas had of always using the same placeholder date.

**Comment by benjamingeer** [comment]
The purpose is what was requested in issue #1397: a timestamp, i.e. a specific date and time with nanosecond precision in the Gregorian calendar. One application could be to implement a custom data versioning system using the timestamps provided with Knora value versions.

I think that if you just want to store a time of day, without a date, this is not the right datatype. Adding fake dates could create confusion and lead to incorrect data reuse. If you just want to store an hour and a minute, let’s design another solution for that.

**Comment by benjamingeer** [comment]
I would like to understand better why there is a need to store a time of day without a date.

**Comment by benjamingeer** [comment]
Examples of timestamps:

- [In POSIX](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/basedefs/V1_chap04.html#tag_04_09), a file timestamp is a number of seconds (or milliseconds, or nanoseconds) since 1 January 1970.
- [In the Oracle database](https://docs.oracle.com/cd/B19306_01/server.102/b14225/ch4datetime.htm#i1006050), "The TIMESTAMP datatype is an extension of the DATE datatype. It stores year, month, day, hour, minute, and second values. It also stores fractional seconds, which are not stored by the DATE datatype."
- In Python, `datetime.now().timestamp()` returns the number of seconds since 1 January 1970, with fractional seconds to nanosecond precision.

**Comment by benjamingeer** [comment]
After discussion with @lrosenth: at the moment we don't need to store a time of day without a date. We have:

- The existing `TimeValue`, which is a timestamp representing a precise instant (a date and time) in modern times. Its GUI component should accept a date and time, and possibly a time zone (converting to UTC to send the timestamp to Knora).
- `IntervalValue`, for a range (a start point and end point) in an audio or video recording.
- `DecimalValue`, which could be used for a specific moment in an audio or video recording.
