### ISSUE TITLE
Allow to configure the attribute that works as "class" attribute in the xml mapping

### ISSUE THREAD

**Issue by mattssp** [dasch-swiss/dsp-api#1729]
When mapping xml to standoff, the same xml-tag can be mapped to different standoff classes by using the "class" attribute. This seems a bit limited, since the "class" attribute is a html attribute and not available, for example, in TEI. So it is not possible to map a tei-tag to more than one standoff-class in a tei-conformant way. I would like to do this to have some tags reference a resource in knora via standoffLinkTag, and others not. E.g. some pb-Tags are linked to a kwa:Page resource, others are not.

An easy way to improve on this would be to allow to define the "classifiing attribute" in the mapping. For tei, e.g., the globally available "type" attribute could be used.

Also note that the class attribute in html can have more than one value (which would not work in knora atm.).

**Comment by benjamingeer** [comment]
ping @tobiasschweizer

**Comment by tobiasschweizer** [comment]
> When mapping xml to standoff, the same xml-tag can be mapped to different standoff classes by using the "class" attribute. This seems a bit limited, since the "class" attribute is a html attribute and not available, for example, in TEI.

That's true since we rather had HTML in mind than XML.

At the moment, we are exploring the possibility of connecting eXist-db to Knora so that TEI-XML files could be uploaded to an instance of eXist-db (see [DSP-task](https://dasch.myjetbrains.com/youtrack/issue/DSP-629)).

Depending on the outcome of this, there is a chance that we are not going to store edited texts in Knora in the future and that the mapping (XML to standoff and vice-versa) would not be necessary anymore.

I think that the current implementation of the mapping is sufficient for simple use cases, i.d. annotations with some formatting etc. but cannot meet the requirements of critical editions such as yours.

There is also a good chance that the client could handle standoff conversions for annotations with a simple mapping mechanism (Knora would not have to do the conversion from and to XML).

Could we maybe present our ideas about how to connect with eXist-db to you to see if this would work for the Walser-edition?
