### ISSUE TITLE
(Search panel : recent searches) Extended search operators

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/dsp-api#226]
![capture d ecran 2016-08-19 a 10 13 30](https://cloud.githubusercontent.com/assets/17294309/17812948/98bd3e80-6629-11e6-9763-862ff976f47a.png)
In « Extended search », the search operators such as the one suggested and the ones currently available in Salsah 1.0 needs to be either completely reconsidered, or clearly explained/defined. Users have expressed their difficulty to understand what these operators mean (most of users are non-mathematicians).

**Comment by milchkannen** [comment]
Yes, we're knowing the issue. There was a documentation about the search operators on wiki.salsah.org. But it's no longer reachable. @subotic can we reactivate the old wiki? Or is it possible to connect the old wiki.salsah.org url the a newer wiki/documentation page? Because the documentation link (question mark icon on salsah.org) is also broken. 
@mrivoal Do you have a better solution for the search operators?

**Comment by mrivoal** [comment]
No, I don't right now. I was hoping that @jroland01 would be give us a hand on that matter. 
But I think it is also part of a much broader question: **redesigning search functionnalities** to allow cross-queries in the GUI. 

As you know, we have to work on this matter with @lrosenth for the **Salsah 1.6** release (planned for february 2017) and I guess (I hope) this could somehow benefit **Salsah 2.0** search design. 

I hope we will be able to provide some suggestions in the next fews weeks regarding that matter, as we investigate a solution/design for Salsah 1.6.

**Comment by jroland01** [comment]
@mrivoal @milchkannen haven't you received my email from Sept. 24th, as a reply to @mrivoal'scomments on @milchkannen's email ? This was part of it:

> - Salsah’s users have had hard time understanding and using mathematical operators, I think we should probably find a better way to deal with them in Salsah 2.

[Julien] : Agree. I see the following approaches in making things clearer, more user friendly :

a) Determine which operators are really useful (which ones are / will actually be used) and remove the others. Again, the extended search will not be able to address every possible query, with every possible level of finesse, so a limit should be put somewhere. Plus there is something called the Paradox of Choice (google "Jam Study" for a good example involving jam !) : The more choices a user has, the less she is prone to actually make a choice. I think this is a typical example where more (operator alternatives) means less ability to select one (which makes the many alternatives useless). 

b) Provide simpler, human -readable, understandable alternatives for the operators : "has the words", "doesn't have the words", "is greater than", "is lower than", etc. are explicit, whereas "match boolean", "like", "exists" (those are from Salsah 1) are far from being explicit. So it's not only about the mathematical, boolean symbol representation, it's also about making sure users understand what the query will actually do (I understand what "like" means, but what does it mean if I say "Price like 200 CHF" ?).

c) Leverage conventions used in other search engines, such as e.g. keywords without punctuation for broad matching, keywords inside quotes for phrase matching, etc. 

@André : Is there an exhaustive list of mathematical, boolean operators somewhere with a description of what they actually do ? Do we have any insights regarding which ones are most used / useful ?

**Comment by jroland01** [comment]
@mrivoal taking the example you've provided at the TOP of the thread (where can you see that full list in Salsah's UI ?), here are some suggestions (but I would need a little bit more context, as well as face-to-face discussions to understand how to best address this) : 

* remove mathematical symbols, as users are mostly non-mathematicians, and mathematicians understand words (the symbols are useless here, and add noise to the interface)

* only keep options in the dropdown that most users will use and understand : e.g. what does" field content match" mean ?

* introduce text modifiers (so symbols that you put into the text field, not in the dropdown) for more advanced users, using conventions or e.g. Lucene -like modifiers (https://goo.gl/11Un94) : * for zero character or more maching, ? for 1 character matching (here : one character, or one digit), keywords only for broad matching, commas for phrase matching (here : literal text), etc.

* simplify available options, e.g. remove "greater than or equal" and "less than or equal", and keep only "greater than" and "less than"

* make some options more explicit, e.g. range --> "is between" 

Key aspects in making this kind of list more efficient for users is : reducing the number of choices ("paradox of choice"), making the most often used options available, making labels explicit and plain, allowing for "gradual discovery" with e.g. text modifiers.

**Comment by mrivoal** [comment]
The screenshot doesn't come from Salsah, it is taken from Filemaker (which is broadly used by humanities researchers). 

Filemaker uses mathematical operators + text modifiers just like Salsah 1.0 did, but Filemaker gives a little bit more explanations for them than Salsah's tooltips do.

You are right, we should try to make them more explicit (and probably even more so than in Filemaker).

**Comment by jroland01** [comment]
Great ! I may have a lead with Apple/FileMaker then ;-) Obviously, if I had known the exact context (e.g. DBMS vs. Virtual Research Environment, any kind of users vs. humanities researchers, which screen does it pertain to in FM ? which version of FM ? etc.) my remarks would have been slightly different for FM. But I think they still hold in the context of Salsah. But of course then you have to add the following point : - add explicit labels as in FileMaker !

As mentioned, it's not only about making things more explicit (that's 1 step), it's also about making choices (more or less visible in the list, merge, remove, keep as dropdown or text modifier, etc.). For both I would definitely need more context, including : 

* an exhaustive list of operators / screen / resource / etc., as well as how their work very concretely
* a bit more details regarding difficulties expressed by users, as per @mrivoal 's initial issue 
* a bit more input regarding which operators are frequently used vs. less frequently used

@mrivoal @milchkannen How do you suggest moving forward ?

**Comment by loicjaouen** [comment]
@jroland01  sorry for deconstructing your questions above:

>  - add explicit labels as in FileMaker !

they are there (hover above the operator and it shows up), but yes, they should be more obvious and maybe replace the math symbols

>  introduce text modifiers (so symbols that you put into the text field, not in the dropdown) for more advanced users, using conventions or e.g. Lucene -like modifiers

Fully agree, maybe maintain a drop down though, as to my knowledge outside of Salsah, people have trouble using the not ("!") operator.

> For both I would definitely need more context, including : 
> an exhaustive list of operators / screen / resource / etc

please have a look at (salsah.org)[salsah.org]

> how their work very concretely

and 

> (I understand what "like" means, but what does it mean if I say "Price like 200 CHF" ?)

please have a look at the [knora doc about search](../tree/develop/docs/rst/knora-api-server/api_v1/reading-and-searching-resources.rst), there you have the list of operators, on which types they are eligible, and what they mean.

> a bit more details regarding difficulties expressed by users

what I heard was mainly complaints about not liking the operators and not understanding the _match_ and _match boolean_ (which unfortunately comes on second position).

> a bit more input regarding which operators are frequently used vs. less frequently used

You know we don't have that ;)

Hoping it helps! Have fun.

**Comment by jroland01** [comment]
Here is a suggestion to start with in order to make Salsah's search operators more user friendly. It's based on https://goo.gl/wgT8w6, as none of the other links seem to work (salsah.org, Salsah's Wiki).


**1 : I have applied the following principles for the suggestion :**
* provide explicit labels in dropdown, remove mathematical symbols, don't rely on tooltips (= admission of failure)
* keep options in dropdown that are used, i.e. well understood and useful for most users (my suggestion is an hypothesis, since we have zero data)
* provide advanced, or more subtle options as term modifiers : more advanced users will use them, other users will discover them progressively as needed
* use de facto conventions for term modifiers (Lucene, Google) so that users can transfer their knowledge
* upgrade a term modifier to its own dropdown menu ONLY if it used by, and brings value to most users


**2 : Some notes regarding the suggestion :**
* I have added Salsah's comparison operator (as per https://goo.gl/iAd4PY) in parenthesis, and that there isn't always a 1-to-1 match with those operators (this is to make the list easier to use, and understandable to users)
* the doc provided doesn't clearly explain the MATCH mode's behavior (match all, match any, etc. ?)


**3 : Here is the list of available options I suggest to start with :**

**is** (EQ) - available for Date, Integer, Float, Resource, Color, List only (DEFAULT)
Can be modified with term modifier : 
* - or NOT for not equal to (!EQ)

**is not** (!EQ) - available for Date, Integer, Float, Resource, Color, List only

**has the words** (MATCH ?, MATCH_BOOLEAN) - available for Text Values only (DEFAULT)
Can be modified with term modifier : 
* "" for phrase matching
* [] for exact (equal to) matching (can be used for EQ)
* - or NOT to exclude results containing the term in the field (can be used for !EQ, and MATCH_BOOLEAN)
* ~ for proximity search (can be used for LIKE)
* also add wildcards (single : ?, multiple : *)

**has any of** (or **any of these words**, or **has any of the words**) (MATCH ?) - available for Text Values only
Can be modified using the same term modifiers as in "has the words" plus :
* + to only include results containing the term in the field

**doesn't have** (or **none of these words**, or **doesn't have the words**) (!EQ) - available for Text Values only
Can be modified with term modifier : 
* "" for phrase matching

**is exactly** (EQ) - available for Text Values only

**is greater than** (GT, GT_EQ)
Can be modified with term modifier : 
* nothing for strictly greater than (GT)
* = for greater than or equal (GT_EQ)

**is lower than** (LT, LT_EQ)
Can be modified with term modifier : 
* nothing for strictly lower than (LT)
* = for lower than or equal (LT_EQ)

**is between** (RANGE)
* add 2 fields separated by "and"

**exists** (EXISTS)
* remove field if this option is selected by the user


**4 : So if we consider them per Value Type, we get the following dropdown options :**

for **Date, Integer, Float** (6 instead of 8 options right now)
* is (default)
* is not
* is greater than
* is lower than
* is between
* exists

for **Text** (4 or 5 instead of 7 options right now)
* has the words (default)
* has any of
* doesn't have
* is exactly (optional)
* exists

for **Geometry** (same as now)
* exists (default)

for **Color**, **List** (same as now)
* is (default)
* exists

@milchkannen @loicjaouen @mrivoal Let me know : 
* what you think ?
* whether this is technically feasible or not ?

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
