### ISSUE TITLE
Simplify Hosting Configuration 

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#251]
When setting up Knora on a server that has an own domain (non localhost), a bunch of (partially redundant) modifications has to be made. Some of them are URLs with or without the port, some of them are just a domain name (without `http://` or port):
- `webapi/src/main/resources/application.conf`: 
  - `app.http.interface`: Knora API URL
  - `app.http.port`: Knora API port 
  - `app.http.base-salsah-url` Salsah webapp URL + port 
  - `app.tmp-datadir`
  - `app.datadir`
  - `app.sipi.url`: Sipi URL
  - `app.sipi.port`: Sipi port
- `salsah/src/main/resources/application.conf`:
  - `app.http.base-knora-url`: Knora API URL + port
- `salsah/src/main/scala/org/knora/salsah/Main.scala`:
  - val (host, port) = ("mySalsahDomain", mySalsahport)
- `salsah/src/public/js/00_init_javascript.js`:
  - var API_URL = 'myKnoraAPIURL:myport';
  - var SIPI_URL = 'mySipiURL:myport';

Can we simplify that and make it more consistent?

**Comment by loicjaouen** [comment]
here are a handful of suggestions of how to avoid direct configuration file editing without using [puppet](https://en.wikipedia.org/wiki/Puppet_%28software%29) or another [configuration management system](https://en.wikipedia.org/wiki/Configuration_management).

# delegate config to docker command line
- use stock docker images
- keep default config values
- delegate config to the docker start command...

by mapping directories to mount points in the docker instance, and proxying local ports to hosted ports in the docker instance.

# proxy web services

As it is all web-services, they are easy to proxy.

# if you have to edit, edit once

heart of a release process:

```
git stash
git pull
git stash apply
```

# reality

I described earlier the set-up we use here, in a now non-readable form (because I didn't use plain text mail):
https://www.maillist.unibas.ch/pipermail/knora-user/2016-July/000079.html

it is a mix of apache web-proxy and git-stash for release (but we plan on using docker).


![set-up-knora](https://cloud.githubusercontent.com/assets/3933654/18312498/56aec898-750a-11e6-887c-c599128e17f1.png)

**Comment by seakayone** [comment]
This issue has been inactive for a significant time, so we’re closing it for now. If it’s still relevant, feel free to reopen.
