### ISSUE TITLE
linking to one resource with a property of cardinality bigger than one  

### ISSUE THREAD

**Issue by SepidehAlassi** [dasch-swiss/dsp-api#284]
Explaining the issue with an example:

considering to have a resource, a Person, which has different names in different languages Jacob, James, Jacques, (multiple entries to property givenName) , another resource, an article, 
should be linked to this person by the author property. In one article the same person is mentioned as Jacob, and in the other article as James.  How the link to the person should find the correct entry (name) to point to?

**Comment by benjamingeer** [comment]
Since there's no way to link directly to a value, I see two options:

1. Make the name a resource rather than a value.
2. Include the author's name in the article resource (redundantly), in addition to the link to the author.

We've talked about ways to make it possible to link directly to a value, but it would be complicated.

**Comment by tobiasschweizer** [comment]
What about storing some additional information in the reification statement?

**Comment by benjamingeer** [comment]
I'd be inclined to make the name a resource, to avoid redundancy, and to allow it to be versioned.
