### ISSUE TITLE
Think about CI friendly HTML automated tests

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/dsp-api#395]
For the old SALSAH, we wrote tests in Selenium (<http://www.seleniumhq.org>).

The tests simulate a user's behavior in the browser. Elements have to be selected by writing XPath expressions.
We experienced the old SALSAH GUI's HTML structure to be very confusing (yes, it's a big pile of crap :-)), so it was hard for us to write those XPath expressions.

Could we define nice naming conventions for classes in the new GUI, so automated tests would be easier to implement?

Example:
You want to test the search. So you have to write an XPath expression that finds the search field, then you have to enter text and click a button or hit the enter key. Then you have to find the results in HTML and check if they are correct.

A problem is timing because requests are async. Selenium offers the `eventually` construct that just retries in case the thing inside it did not work out. Perhaps there is a better way instead of this brute force method (e.g. here: https://spin.atomicobject.com/2015/05/12/testing-asynchronous-behavior-javascript-selenium/). It would be really nice to look at the results of async calls in detail instead of looking only at the resulting HTML.

I have recently tried `executeScript` that runs JavaScript in the browser (http://stackoverflow.com/questions/11430773/how-to-use-javascript-with-selenium-webdriver-using-java).

**Comment by subotic** [comment]
I hope that this will not be an issue with Salsah 2.0, as it is AngularJS based. We just need to set up testing from the beginning:

 - Unit testing: https://docs.angularjs.org/guide/unit-testing
 - Selenium: http://www.protractortest.org

Also, the browser tests need to be able to run in headless mode (without an open browser window), so that they can run on Travis.

**Comment by tobiasschweizer** [comment]
Good point. Yes, we should add tests from the very beginning this time.

And also run them ;-)

**Comment by subotic** [comment]
That's why they need to work on Travis. If I don't run them, Travis will for sure :-)

**Comment by andreas-aeschlimann** [comment]
@tobiasschweizer @subotic it shouldn't be a problem to write Angular 2 tests, as there are several possibilities to do so: https://angular.io/docs/ts/latest/guide/testing.html

But it is true that we should start early with it, otherwise you will never do it properly. I'll ask @kilchenmann what he has planned when we meet next time.

Imo testing should be easier than before because the project structure itself should be much better within the Angular 2 project. And we also have compilation of the code (TypeScript) and strict API testing (json2typescript).
